name: Publish to NPM

on:
  workflow_run:
    workflows: ["Release to GitHub"] # Name of the workflow to wait for
    types: [completed]
    branches: [main]

jobs:
  publish-npm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write  # For npm provenance
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Verify bin directory is clean
        run: |
          # Ensure bin directory only has .gitkeep
          if [ -d "bin" ]; then
            file_count=$(find bin -type f ! -name '.gitkeep' | wc -l)
            if [ $file_count -gt 0 ]; then
              echo "Error: bin directory contains files. It should only have .gitkeep"
              exit 1
            fi
          else
            mkdir -p bin
            touch bin/.gitkeep
          fi

      - name: Test npm package
        run: npm test

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
