name: Publish to JSR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_run:
    workflows: ["Test Deno"]
    types:
      - completed
    branches:
      - main

jobs:
  publish-jsr:
    if: >
      github.event_name == 'push' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Log workflow context
        run: |
          echo "Publishing to JSR for tag: ${GITHUB_REF#refs/tags/}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Triggered by: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            echo "After successful Test Deno workflow"
          fi
          
      - name: Verify deno.json exists
        run: |
          if [ ! -f "deno.json" ]; then
            echo "ERROR: deno.json not found in repository root"
            exit 1
          fi
          echo "✓ Found deno.json"
          echo "Package info:"
          cat deno.json | grep -E '"name"|"version"' || true

      - name: Publish to JSR
        run: |
          echo "Publishing to JSR registry..."
          npx jsr publish
          echo "✓ Successfully published to JSR"
